## 1. Reading and Cleaning Data

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv('New_York_reviews.csv')
df.head()

/var/folders/11/cxk41wc10_xff4v0c3jx2bb80000gn/T/ipykernel_11258/3967909716.py:1: DtypeWarning: Columns (0,1,3) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('New_York_reviews.csv')


Unnamed: 0 parse_count restaurant_name rating_review    sample  \
0          1           2            Lido             5  Positive   
1          2           3            Lido             4  Positive   
2          3           4            Lido             1  Negative   
3          4           5            Lido             5  Positive   
4          5           6            Lido             5  Positive   

          review_id             title_review  \
0  review_773559838          A Regular Treat   
1  review_769429529  Good neighborhood spot!   
2  review_745700258            Disappointing   
3  review_728859349    What a find in Harlem   
4  review_728429643                    Lunch   

                                      review_preview  \
0  My wife and I have been eating dinner frequent...   
1  Came with family for Labor Day weekend brunch ...   
2  Food was mediocre at best.  The lamb chops are...   
3  My co-workers were volunteering at a foodbank ...   
4  Lido is an intimate boutique style restaurant....   

                                         review_full               date  \
0  My wife and I have been eating dinner frequent...    October 8, 2020   
1  Came with family for Labor Day weekend brunch ...  September 8, 2020   
2  Food was mediocre at best. The lamb chops are ...  February 17, 2020   
3  My co-workers were volunteering at a foodbank ...  November 25, 2019   
4  Lido is an intimate boutique style restaurant....  November 23, 2019   

                     city                                     url_restaurant  \
0  New_York_City_New_York  https://www.tripadvisor.com/Restaurant_Review-...   
1  New_York_City_New_York  https://www.tripadvisor.com/Restaurant_Review-...   
2  New_York_City_New_York  https://www.tripadvisor.com/Restaurant_Review-...   
3  New_York_City_New_York  https://www.tripadvisor.com/Restaurant_Review-...   
4  New_York_City_New_York  https://www.tripadvisor.com/Restaurant_Review-...   

  author_id  
0     UID_0  
1     UID_1  
2     UID_2  
3     UID_3  
4     UID_4

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 510463 entries, 0 to 510462
Data columns (total 13 columns):
 #   Column           Non-Null Count   Dtype 
---  ------           --------------   ----- 
 0   Unnamed: 0       510463 non-null  object
 1   parse_count      510463 non-null  object
 2   restaurant_name  510463 non-null  object
 3   rating_review    510463 non-null  object
 4   sample           510463 non-null  object
 5   review_id        510463 non-null  object
 6   title_review     510462 non-null  object
 7   review_preview   510462 non-null  object
 8   review_full      510461 non-null  object
 9   date             510461 non-null  object
 10  city             510461 non-null  object
 11  url_restaurant   510461 non-null  object
 12  author_id        510461 non-null  object
dtypes: object(13)
memory usage: 50.6+ MB


In [4]:
df['rating_review'].value_counts()

5                         227762
4                         138785
3                          46988
5                          31210
4                          22006
2                          17553
1                          13839
3                           7356
2                           2759
1                           2204
New_York_City_New_York         1
Name: rating_review, dtype: int64

In [5]:
df = df[['rating_review', 'review_full']]
df.head()

rating_review                                        review_full
0             5  My wife and I have been eating dinner frequent...
1             4  Came with family for Labor Day weekend brunch ...
2             1  Food was mediocre at best. The lamb chops are ...
3             5  My co-workers were volunteering at a foodbank ...
4             5  Lido is an intimate boutique style restaurant....

In [6]:
# droping a row that df['rating_review']='New_York_City_New_York'
df = df.drop(df['rating_review'].loc[df['rating_review']=='New_York_City_New_York'].index)

In [7]:
df.rating_review.value_counts()

5    227762
4    138785
3     46988
5     31210
4     22006
2     17553
1     13839
3      7356
2      2759
1      2204
Name: rating_review, dtype: int64

In [8]:
df['rating_review']= pd.to_numeric(df['rating_review'])

In [9]:
df.rating_review.value_counts()

5    258972
4    160791
3     54344
2     20312
1     16043
Name: rating_review, dtype: int64

In [10]:
df['review_full'] = df['review_full'].astype(str)

In [11]:
X = df.review_full
y = df.rating_review
print(X.shape)
print(y.shape)

(510462,)
(510462,)


In [12]:
# split X and y into training and testing sets
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=123)
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(382846,)
(127616,)
(382846,)
(127616,)


## 2. Vectorizing the dataset

In [13]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf_1 = TfidfVectorizer()

In [14]:
# Learning training data vocabulary, and use to transform X_train to document-term matrix

X_train_dtm = tfidf_1.fit_transform(X_train)
X_train_dtm

<382846x109698 sparse matrix of type '<class 'numpy.float64'>'
	with 21485371 stored elements in Compressed Sparse Row format>

In [15]:
X_test_dtm = tfidf_1.transform(X_test)
X_test_dtm

<127616x109698 sparse matrix of type '<class 'numpy.float64'>'
	with 7147220 stored elements in Compressed Sparse Row format>

In [16]:
df_x_train = pd.DataFrame.sparse.from_spmatrix(X_train_dtm,columns=tfidf_1.get_feature_names_out())
df_x_train

00  000  0000  00000027  000075  0007  000c  000k  000km  000s  ...  \
0       0.0  0.0   0.0       0.0     0.0   0.0   0.0   0.0    0.0   0.0  ...   
1       0.0  0.0   0.0       0.0     0.0   0.0   0.0   0.0    0.0   0.0  ...   
2       0.0  0.0   0.0       0.0     0.0   0.0   0.0   0.0    0.0   0.0  ...   
3       0.0  0.0   0.0       0.0     0.0   0.0   0.0   0.0    0.0   0.0  ...   
4       0.0  0.0   0.0       0.0     0.0   0.0   0.0   0.0    0.0   0.0  ...   
...     ...  ...   ...       ...     ...   ...   ...   ...    ...   ...  ...   
382841  0.0  0.0   0.0       0.0     0.0   0.0   0.0   0.0    0.0   0.0  ...   
382842  0.0  0.0   0.0       0.0     0.0   0.0   0.0   0.0    0.0   0.0  ...   
382843  0.0  0.0   0.0       0.0     0.0   0.0   0.0   0.0    0.0   0.0  ...   
382844  0.0  0.0   0.0       0.0     0.0   0.0   0.0   0.0    0.0   0.0  ...   
382845  0.0  0.0   0.0       0.0     0.0   0.0   0.0   0.0    0.0   0.0  ...   

         ｏｆ  ｏｖｅｒｈｅａｄ  ｐｏｉｎｔ  ｒｏｃｋ  ｓｉｄｅ  ｔｈｅ   ｔｏ  ｔｗｏ  ｗｈｅｒｅ  ｗｏｒｄｓ  
0       0.0       0.0    0.0   0.0   0.0  0.0  0.0  0.0    0.0    0.0  
1       0.0       0.0    0.0   0.0   0.0  0.0  0.0  0.0    0.0    0.0  
2       0.0       0.0    0.0   0.0   0.0  0.0  0.0  0.0    0.0    0.0  
3       0.0       0.0    0.0   0.0   0.0  0.0  0.0  0.0    0.0    0.0  
4       0.0       0.0    0.0   0.0   0.0  0.0  0.0  0.0    0.0    0.0  
...     ...       ...    ...   ...   ...  ...  ...  ...    ...    ...  
382841  0.0       0.0    0.0   0.0   0.0  0.0  0.0  0.0    0.0    0.0  
382842  0.0       0.0    0.0   0.0   0.0  0.0  0.0  0.0    0.0    0.0  
382843  0.0       0.0    0.0   0.0   0.0  0.0  0.0  0.0    0.0    0.0  
382844  0.0       0.0    0.0   0.0   0.0  0.0  0.0  0.0    0.0    0.0  
382845  0.0       0.0    0.0   0.0   0.0  0.0  0.0  0.0    0.0    0.0  

[382846 rows x 109698 columns]

In [17]:
vec1=df_x_train.head(1).sparse.to_dense().iloc[0]
vec1.sort_values()

00           0.000000
piperies     0.000000
piperia      0.000000
piperade     0.000000
piper        0.000000
               ...   
fix          0.207838
blueberry    0.221858
your         0.224024
pancake      0.225394
mum          0.257732
Name: 0, Length: 109698, dtype: float64

In [18]:
vec2 = df_x_train.head(2).sparse.to_dense().iloc[1]
vec2.sort_values()

00          0.000000
pipi        0.000000
pipette     0.000000
pipes       0.000000
pipers      0.000000
              ...   
cocktail    0.208373
greeted     0.225292
by          0.236344
was         0.286036
who         0.305903
Name: 1, Length: 109698, dtype: float64

## 3. Building and evaluating  a model

In [19]:
# import and instantiate a Logistic regressional
from sklearn.linear_model import LogisticRegression
logreg = LogisticRegression(max_iter=1000)

In [20]:
# train the model using X_train_dtm
logreg.fit(X_train_dtm, y_train)

LogisticRegression(max_iter=1000)

In [21]:
y_train_pred = logreg.predict(X_train_dtm)

In [22]:
# getting training data's accuracy score
from sklearn import metrics
metrics.accuracy_score(y_train, y_train_pred)

0.7150002873217952

In [23]:
# make class predictions for X_test_dtm
y_pred = logreg.predict(X_test_dtm)

In [24]:
# print the confusion matrix
print(metrics.confusion_matrix(y_test, y_pred))

[[ 2264   841   600   124   177]
 [  934  1369  2124   412   213]
 [  407   824  6976  4320  1070]
 [   85    92  2373 20812 17048]
 [   31    23   327 10149 54021]]


In [25]:
# print the classification report
print(metrics.classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           1       0.61      0.57      0.59      4006
           2       0.43      0.27      0.33      5052
           3       0.56      0.51      0.54     13597
           4       0.58      0.52      0.55     40410
           5       0.74      0.84      0.79     64551

    accuracy                           0.67    127616
   macro avg       0.59      0.54      0.56    127616
weighted avg       0.66      0.67      0.66    127616



## 4. Hyperparameter tuning

In [26]:
# 2. Using stop_words = 'english' as a hyperparameter 
tfidf_2 = TfidfVectorizer(stop_words='english')
X_train_2 =tfidf_2.fit_transform(X_train)
X_test_2 = tfidf_2.transform(X_test)

In [27]:
logreg_2 = LogisticRegression(max_iter=1000)
y_pred_2=logreg_2.fit(X_train_2, y_train).predict(X_test_2)
y_train_pred2 = logreg_2.predict(X_train_2)

In [28]:
# 3. Usinng max_df = 0.50 "ignore terms that appear in more than 50% of the documents"
tfidf_3 = TfidfVectorizer(max_df = 0.50)
X_train_3 = tfidf_3.fit_transform(X_train)
X_test_3 = tfidf_3.transform(X_test)

In [29]:
logreg_3 = LogisticRegression(max_iter=1000)
y_pred_3 = logreg_3.fit(X_train_3, y_train).predict(X_test_3)
y_train_pred3 = logreg_3.predict(X_train_3)

In [30]:
# Using min_df = 5 "ignore terms that appear in less than 25% of the documents"
tfidf_4 = TfidfVectorizer(min_df=5)
X_train_4 = tfidf_4.fit_transform(X_train)
X_test_4 = tfidf_4.transform(X_test)

In [31]:
logreg_4 = LogisticRegression(max_iter=1000)
y_pred_4 = logreg_4.fit(X_train_4, y_train).predict(X_test_4)
y_train_pred4 = logreg_4.predict(X_train_4)

In [32]:
# Creating hyperparameter table
hyperparameter_table = []
def trip_adviser_model(model,y_test, y_pred, y_train, y_train_pred,  tfidf):

    
    hyper_paramteres = {}
    hyper_paramteres['model'] = str(type(model))
    hyper_paramteres['max_df'] =tfidf.max_df
    hyper_paramteres['min_df'] = tfidf.min_df
    hyper_paramteres['stop_words'] = tfidf.stop_words
    hyper_paramteres['Training accuracy score'] = metrics.accuracy_score(y_train, y_train_pred)
    hyper_paramteres['Testing accuracy score'] = metrics.accuracy_score(y_test, y_pred)
    hyper_paramteres['F1'] = metrics.f1_score(y_test, y_pred, average = 'weighted')
    hyperparameter_table.append(hyper_paramteres)
    return pd.DataFrame(hyperparameter_table)

In [33]:
trip_adviser_model(logreg, y_test, y_pred, y_train, y_train_pred, tfidf_1)

model  max_df  min_df  \
0  <class 'sklearn.linear_model._logistic.Logisti...     1.0       1   

  stop_words  Training accuracy score  Testing accuracy score        F1  
0       None                    0.715                0.669524  0.660375

In [34]:
trip_adviser_model(logreg_2, y_test, y_pred_2,y_train, y_train_pred2, tfidf_2)

model  max_df  min_df  \
0  <class 'sklearn.linear_model._logistic.Logisti...     1.0       1   
1  <class 'sklearn.linear_model._logistic.Logisti...     1.0       1   

  stop_words  Training accuracy score  Testing accuracy score        F1  
0       None                 0.715000                0.669524  0.660375  
1    english                 0.708609                0.657135  0.646279

In [35]:
trip_adviser_model(logreg_3, y_test, y_pred_3,y_train, y_train_pred3, tfidf_3)

model  max_df  min_df  \
0  <class 'sklearn.linear_model._logistic.Logisti...     1.0       1   
1  <class 'sklearn.linear_model._logistic.Logisti...     1.0       1   
2  <class 'sklearn.linear_model._logistic.Logisti...     0.5       1   

  stop_words  Training accuracy score  Testing accuracy score        F1  
0       None                 0.715000                0.669524  0.660375  
1    english                 0.708609                0.657135  0.646279  
2       None                 0.715076                0.668357  0.659071

In [36]:
trip_adviser_model(logreg_4, y_test, y_pred_4,y_train, y_train_pred4, tfidf_4)

model  max_df  min_df  \
0  <class 'sklearn.linear_model._logistic.Logisti...     1.0       1   
1  <class 'sklearn.linear_model._logistic.Logisti...     1.0       1   
2  <class 'sklearn.linear_model._logistic.Logisti...     0.5       1   
3  <class 'sklearn.linear_model._logistic.Logisti...     1.0       5   

  stop_words  Training accuracy score  Testing accuracy score        F1  
0       None                 0.715000                0.669524  0.660375  
1    english                 0.708609                0.657135  0.646279  
2       None                 0.715076                0.668357  0.659071  
3       None                 0.707914                0.669414  0.660260

## 5. Comparing models

#### 4.1 First model

In [37]:
# import and run a Multinomial Naive Bayes model
from sklearn.naive_bayes import MultinomialNB
nb = MultinomialNB()

In [38]:
# train the model using X_train_dtm
nb.fit(X_train_dtm,y_train)

MultinomialNB()

In [39]:
y_pred1 = nb.predict(X_test_dtm)

In [40]:
y_train_pred11 = nb.predict(X_train_dtm)

#### 4.2 Second model

In [41]:
from sklearn.linear_model import SGDClassifier
sgd_classifier = SGDClassifier()

In [42]:
sgd_classifier.fit(X_train_dtm, y_train)

SGDClassifier()

In [43]:
y_pred2 = sgd_classifier.predict(X_test_dtm)
y_train_pred22 = sgd_classifier.predict(X_train_dtm)

In [44]:
trip_adviser_model(nb, y_test,y_pred1, y_train, y_train_pred11, tfidf_1)

model  max_df  min_df  \
0  <class 'sklearn.linear_model._logistic.Logisti...     1.0       1   
1  <class 'sklearn.linear_model._logistic.Logisti...     1.0       1   
2  <class 'sklearn.linear_model._logistic.Logisti...     0.5       1   
3  <class 'sklearn.linear_model._logistic.Logisti...     1.0       5   
4        <class 'sklearn.naive_bayes.MultinomialNB'>     1.0       1   

  stop_words  Training accuracy score  Testing accuracy score        F1  
0       None                 0.715000                0.669524  0.660375  
1    english                 0.708609                0.657135  0.646279  
2       None                 0.715076                0.668357  0.659071  
3       None                 0.707914                0.669414  0.660260  
4       None                 0.569884                0.549453  0.447217

In [45]:
nlp_results =  trip_adviser_model(sgd_classifier, y_test, y_pred2,y_train, y_train_pred22, tfidf_1)

In [46]:
nlp_results

model  max_df  min_df  \
0  <class 'sklearn.linear_model._logistic.Logisti...     1.0       1   
1  <class 'sklearn.linear_model._logistic.Logisti...     1.0       1   
2  <class 'sklearn.linear_model._logistic.Logisti...     0.5       1   
3  <class 'sklearn.linear_model._logistic.Logisti...     1.0       5   
4        <class 'sklearn.naive_bayes.MultinomialNB'>     1.0       1   
5  <class 'sklearn.linear_model._stochastic_gradi...     1.0       1   

  stop_words  Training accuracy score  Testing accuracy score        F1  
0       None                 0.715000                0.669524  0.660375  
1    english                 0.708609                0.657135  0.646279  
2       None                 0.715076                0.668357  0.659071  
3       None                 0.707914                0.669414  0.660260  
4       None                 0.569884                0.549453  0.447217  
5       None                 0.635545                0.629278  0.584332

In [47]:
nlp_results.to_csv("tripadviser_results")